language: go
go:
  - 1.8.x
  - 1.9.x
go_import_path: github.com/ildarusmanov/eventmapper
services:
  - rabbitmq
env:
  - AMQP_URL=amqp://guest:guest@127.0.0.1:5672/
script:
  - go test -cpu=1,2 -v ./models/ ./controllers/ ./mq/
