language: go
go:
  - 1.8.x
  - 1.9.x
services:
  - rabbitmq
env:
  - AMQP_URL=amqp://guest:guest@127.0.0.1:5672/
script:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - go test -cpu=1,2 -v ./models/ ./controllers/ ./mq/
