server_host: "127.0.0.1:8000"
auth_token: "super-token"
mq_url: "amqp://guest:guest@localhost:5672"
mq_handlers:
  - mq_url: "amqp://guest:guest@localhost:5672"
    r_key: "apply_test.*"
    handler_type: "http_json"
    url: "http://0.0.0.0:5000"
